/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// EddsaEd25519Signature
    /// </summary>
    [DataContract]
    public partial class EddsaEd25519Signature : Signature,  IEquatable<EddsaEd25519Signature>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EddsaEd25519Signature" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EddsaEd25519Signature() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EddsaEd25519Signature" /> class.
        /// </summary>
        /// <param name="signature">The hex-encoded 64-byte long recovery id and signature of an EDDSA Ed25519 key-pair (required).</param>
        public EddsaEd25519Signature(string signature = default(string)) : base(type)
        {
            // to ensure "signature" is required (not null)
            if (signature == null)
            {
                throw new InvalidDataException("signature is a required property for EddsaEd25519Signature and cannot be null");
            }
            else
            {
                this.Signature = signature;
            }

        }

        /// <summary>
        /// The hex-encoded 64-byte long recovery id and signature of an EDDSA Ed25519 key-pair
        /// </summary>
        /// <value>The hex-encoded 64-byte long recovery id and signature of an EDDSA Ed25519 key-pair</value>
        [DataMember(Name="signature", EmitDefaultValue=true)]
        public string Signature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EddsaEd25519Signature {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EddsaEd25519Signature);
        }

        /// <summary>
        /// Returns true if EddsaEd25519Signature instances are equal
        /// </summary>
        /// <param name="input">Instance of EddsaEd25519Signature to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EddsaEd25519Signature input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Signature == input.Signature ||
                    (this.Signature != null &&
                    this.Signature.Equals(input.Signature))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Signature != null)
                    hashCode = hashCode * 59 + this.Signature.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;
            // Signature (string) maxLength
            if(this.Signature != null && this.Signature.Length > 128)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Signature, length must be less than 128.", new [] { "Signature" });
            }

            // Signature (string) minLength
            if(this.Signature != null && this.Signature.Length < 128)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Signature, length must be greater than 128.", new [] { "Signature" });
            }

            yield break;
        }
    }

}
