/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A request to extract the ABI from the package&#39;s hex-encoded WASM binrary
    /// </summary>
    [DataContract]
    public partial class ExtractAbiRequest :  IEquatable<ExtractAbiRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractAbiRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ExtractAbiRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractAbiRequest" /> class.
        /// </summary>
        /// <param name="packageWasm">A hex-encoded string of the package WASM binary (required).</param>
        public ExtractAbiRequest(string packageWasm = default(string))
        {
            // to ensure "packageWasm" is required (not null)
            if (packageWasm == null)
            {
                throw new InvalidDataException("packageWasm is a required property for ExtractAbiRequest and cannot be null");
            }
            else
            {
                this.PackageWasm = packageWasm;
            }

        }

        /// <summary>
        /// A hex-encoded string of the package WASM binary
        /// </summary>
        /// <value>A hex-encoded string of the package WASM binary</value>
        [DataMember(Name="package_wasm", EmitDefaultValue=true)]
        public string PackageWasm { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExtractAbiRequest {\n");
            sb.Append("  PackageWasm: ").Append(PackageWasm).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExtractAbiRequest);
        }

        /// <summary>
        /// Returns true if ExtractAbiRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ExtractAbiRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExtractAbiRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PackageWasm == input.PackageWasm ||
                    (this.PackageWasm != null &&
                    this.PackageWasm.Equals(input.PackageWasm))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PackageWasm != null)
                    hashCode = hashCode * 59 + this.PackageWasm.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
