/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The response returned from an &#x60;InformationRequest&#x60;. This response contains the version of the transaction library currently in use.
    /// </summary>
    [DataContract]
    public partial class InformationResponse :  IEquatable<InformationResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InformationResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InformationResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InformationResponse" /> class.
        /// </summary>
        /// <param name="packageVersion">packageVersion (required).</param>
        public InformationResponse(string packageVersion = default(string))
        {
            // to ensure "packageVersion" is required (not null)
            if (packageVersion == null)
            {
                throw new InvalidDataException("packageVersion is a required property for InformationResponse and cannot be null");
            }
            else
            {
                this.PackageVersion = packageVersion;
            }

        }

        /// <summary>
        /// Gets or Sets PackageVersion
        /// </summary>
        [DataMember(Name="package_version", EmitDefaultValue=true)]
        public string PackageVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InformationResponse {\n");
            sb.Append("  PackageVersion: ").Append(PackageVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InformationResponse);
        }

        /// <summary>
        /// Returns true if InformationResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of InformationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InformationResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PackageVersion == input.PackageVersion ||
                    (this.PackageVersion != null &&
                    this.PackageVersion.Equals(input.PackageVersion))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PackageVersion != null)
                    hashCode = hashCode * 59 + this.PackageVersion.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
