/*
 * Transaction Lib
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Models
{
    /// <summary>
    /// CallFunction
    /// </summary>
    [DataContract]
    public partial class CallFunction : Instruction, IEquatable<CallFunction>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CallFunction" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CallFunction() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CallFunction" /> class.
        /// </summary>
        /// <param name="packageAddress">packageAddress (required).</param>
        /// <param name="blueprintName">blueprintName (required).</param>
        /// <param name="functionName">functionName (required).</param>
        /// <param name="arguments">arguments (required).</param>
        public CallFunction(PackageAddress packageAddress = default(PackageAddress), String blueprintName = default(String), String functionName = default(String), List<Value> arguments = default(List<Value>)) : base("CALL_FUNCTION")
        {
            // to ensure "packageAddress" is required (not null)
            if (packageAddress == null)
            {
                throw new InvalidDataException("packageAddress is a required property for CallFunction and cannot be null");
            }
            else
            {
                this.PackageAddress = packageAddress;
            }

            // to ensure "blueprintName" is required (not null)
            if (blueprintName == null)
            {
                throw new InvalidDataException("blueprintName is a required property for CallFunction and cannot be null");
            }
            else
            {
                this.BlueprintName = blueprintName;
            }

            // to ensure "functionName" is required (not null)
            if (functionName == null)
            {
                throw new InvalidDataException("functionName is a required property for CallFunction and cannot be null");
            }
            else
            {
                this.FunctionName = functionName;
            }

            // to ensure "arguments" is required (not null)
            if (arguments == null)
            {
                throw new InvalidDataException("arguments is a required property for CallFunction and cannot be null");
            }
            else
            {
                this.Arguments = arguments;
            }

            this.Arguments = arguments;
        }

        /// <summary>
        /// Gets or Sets PackageAddress
        /// </summary>
        [DataMember(Name = "package_address", EmitDefaultValue = true)]
        public PackageAddress PackageAddress { get; set; }

        /// <summary>
        /// Gets or Sets BlueprintName
        /// </summary>
        [DataMember(Name = "blueprint_name", EmitDefaultValue = true)]
        public String BlueprintName { get; set; }

        /// <summary>
        /// Gets or Sets FunctionName
        /// </summary>
        [DataMember(Name = "function_name", EmitDefaultValue = true)]
        public String FunctionName { get; set; }

        /// <summary>
        /// Gets or Sets Arguments
        /// </summary>
        [DataMember(Name = "arguments", EmitDefaultValue = true)]
        public List<Value> Arguments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CallFunction {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  PackageAddress: ").Append(PackageAddress).Append("\n");
            sb.Append("  BlueprintName: ").Append(BlueprintName).Append("\n");
            sb.Append("  FunctionName: ").Append(FunctionName).Append("\n");
            sb.Append("  Arguments: ").Append(Arguments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CallFunction);
        }

        /// <summary>
        /// Returns true if CallFunction instances are equal
        /// </summary>
        /// <param name="input">Instance of CallFunction to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CallFunction input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                (
                    this.PackageAddress == input.PackageAddress ||
                    (this.PackageAddress != null &&
                    this.PackageAddress.Equals(input.PackageAddress))
                ) && base.Equals(input) &&
                (
                    this.BlueprintName == input.BlueprintName ||
                    (this.BlueprintName != null &&
                    this.BlueprintName.Equals(input.BlueprintName))
                ) && base.Equals(input) &&
                (
                    this.FunctionName == input.FunctionName ||
                    (this.FunctionName != null &&
                    this.FunctionName.Equals(input.FunctionName))
                ) && base.Equals(input) &&
                (
                    this.Arguments == input.Arguments ||
                    this.Arguments != null &&
                    input.Arguments != null &&
                    this.Arguments.SequenceEqual(input.Arguments)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.PackageAddress != null)
                    hashCode = hashCode * 59 + this.PackageAddress.GetHashCode();
                if (this.BlueprintName != null)
                    hashCode = hashCode * 59 + this.BlueprintName.GetHashCode();
                if (this.FunctionName != null)
                    hashCode = hashCode * 59 + this.FunctionName.GetHashCode();
                if (this.Arguments != null)
                    hashCode = hashCode * 59 + this.Arguments.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
