/*
 * Transaction Lib
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Models
{
    /// <summary>
    /// CompileNotarizedTransactionIntentResponse
    /// </summary>
    [DataContract]
    public partial class CompileNotarizedTransactionIntentResponse :  IEquatable<CompileNotarizedTransactionIntentResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompileNotarizedTransactionIntentResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CompileNotarizedTransactionIntentResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CompileNotarizedTransactionIntentResponse" /> class.
        /// </summary>
        /// <param name="compiledNotarizedIntent">compiledNotarizedIntent (required).</param>
        public CompileNotarizedTransactionIntentResponse(string compiledNotarizedIntent = default(string))
        {
            // to ensure "compiledNotarizedIntent" is required (not null)
            if (compiledNotarizedIntent == null)
            {
                throw new InvalidDataException("compiledNotarizedIntent is a required property for CompileNotarizedTransactionIntentResponse and cannot be null");
            }
            else
            {
                this.CompiledNotarizedIntent = compiledNotarizedIntent;
            }

        }

        /// <summary>
        /// Gets or Sets CompiledNotarizedIntent
        /// </summary>
        [DataMember(Name="compiled_notarized_intent", EmitDefaultValue=true)]
        public string CompiledNotarizedIntent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CompileNotarizedTransactionIntentResponse {\n");
            sb.Append("  CompiledNotarizedIntent: ").Append(CompiledNotarizedIntent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CompileNotarizedTransactionIntentResponse);
        }

        /// <summary>
        /// Returns true if CompileNotarizedTransactionIntentResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CompileNotarizedTransactionIntentResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CompileNotarizedTransactionIntentResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CompiledNotarizedIntent == input.CompiledNotarizedIntent ||
                    (this.CompiledNotarizedIntent != null &&
                    this.CompiledNotarizedIntent.Equals(input.CompiledNotarizedIntent))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CompiledNotarizedIntent != null)
                    hashCode = hashCode * 59 + this.CompiledNotarizedIntent.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
