/*
 * Transaction Lib
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;

namespace Models
{
    /// <summary>
    /// Instruction
    /// </summary>
    [DataContract]
    [JsonConverter(typeof(JsonSubtypes), "instruction")]
    [JsonSubtypes.KnownSubType(typeof(AssertWorktopContains), "ASSERT_WORKTOP_CONTAINS")]
    [JsonSubtypes.KnownSubType(typeof(AssertWorktopContainsByAmount), "ASSERT_WORKTOP_CONTAINS_BY_AMOUNT")]
    [JsonSubtypes.KnownSubType(typeof(AssertWorktopContainsByIds), "ASSERT_WORKTOP_CONTAINS_BY_IDS")]
    [JsonSubtypes.KnownSubType(typeof(CallFunction), "CALL_FUNCTION")]
    [JsonSubtypes.KnownSubType(typeof(CallMethod), "CALL_METHOD")]
    [JsonSubtypes.KnownSubType(typeof(CallMethodWithAllResources), "CALL_METHOD_WITH_ALL_RESOURCES")]
    [JsonSubtypes.KnownSubType(typeof(ClearAuthZone), "CLEAR_AUTH_ZONE")]
    [JsonSubtypes.KnownSubType(typeof(CloneProof), "CLONE_PROOF")]
    [JsonSubtypes.KnownSubType(typeof(CreateProofFromAuthZone), "CREATE_PROOF_FROM_AUTH_ZONE")]
    [JsonSubtypes.KnownSubType(typeof(CreateProofFromAuthZoneByAmount), "CREATE_PROOF_FROM_AUTH_ZONE_BY_AMOUNT")]
    [JsonSubtypes.KnownSubType(typeof(CreateProofFromAuthZoneByIds), "CREATE_PROOF_FROM_AUTH_ZONE_BY_IDS")]
    [JsonSubtypes.KnownSubType(typeof(CreateProofFromBucket), "CREATE_PROOF_FROM_BUCKET")]
    [JsonSubtypes.KnownSubType(typeof(DropAllProofs), "DROP_ALL_PROOF")]
    [JsonSubtypes.KnownSubType(typeof(DropProof), "DROP_PROOF")]
    [JsonSubtypes.KnownSubType(typeof(PopFromAuthZone), "POP_FROM_AUTH_ZONE")]
    [JsonSubtypes.KnownSubType(typeof(PublishPackage), "PUBLISH_PACKAGE")]
    [JsonSubtypes.KnownSubType(typeof(PushToAuthZone), "PUSH_TO_AUTH_ZONE")]
    [JsonSubtypes.KnownSubType(typeof(ReturnToWorktop), "RETURN_TO_WORKTOP")]
    [JsonSubtypes.KnownSubType(typeof(TakeFromWorktop), "TAKE_FROM_WORKTOP")]
    [JsonSubtypes.KnownSubType(typeof(TakeFromWorktopByAmount), "TAKE_FROM_WORKTOP_BY_AMOUNT")]
    [JsonSubtypes.KnownSubType(typeof(TakeFromWorktopByIds), "TAKE_FROM_WORKTOP_BY_IDS")]
    public partial class Instruction :  IEquatable<Instruction>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Instruction" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public Instruction(string value = default(string)){
			this._Instruction = value;
		}

        /// <summary>
        /// Gets or Sets _Instruction
        /// </summary>
        [DataMember(Name="instruction", EmitDefaultValue=true)]
        public string _Instruction { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Instruction {\n");
            sb.Append("  _Instruction: ").Append(_Instruction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Instruction);
        }

        /// <summary>
        /// Returns true if Instruction instances are equal
        /// </summary>
        /// <param name="input">Instance of Instruction to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Instruction input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._Instruction == input._Instruction ||
                    (this._Instruction != null &&
                    this._Instruction.Equals(input._Instruction))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Instruction != null)
                    hashCode = hashCode * 59 + this._Instruction.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
