/*
 * Transaction Lib
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Models
{
    /// <summary>
    /// PublishPackageAllOf
    /// </summary>
    [DataContract]
    public partial class PublishPackageAllOf : IEquatable<PublishPackageAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublishPackageAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PublishPackageAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PublishPackageAllOf" /> class.
        /// </summary>
        /// <param name="package">package (required).</param>
        public PublishPackageAllOf(Bytes package = default(Bytes))
        {
            // to ensure "package" is required (not null)
            if (package == null)
            {
                throw new InvalidDataException("package is a required property for PublishPackageAllOf and cannot be null");
            }
            else
            {
                this.Package = package;
            }

        }

        /// <summary>
        /// Gets or Sets Package
        /// </summary>
        [DataMember(Name = "package", EmitDefaultValue = true)]
        public Bytes Package { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PublishPackageAllOf {\n");
            sb.Append("  Package: ").Append(Package).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PublishPackageAllOf);
        }

        /// <summary>
        /// Returns true if PublishPackageAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of PublishPackageAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PublishPackageAllOf input)
        {
            if (input == null)
                return false;

            return
                (
                    this.Package == input.Package ||
                    (this.Package != null &&
                    this.Package.Equals(input.Package))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Package != null)
                    hashCode = hashCode * 59 + this.Package.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
