/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CallFunctionAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CallFunctionAllOfTests
    {
        // TODO uncomment below to declare an instance variable for CallFunctionAllOf
        //private CallFunctionAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallFunctionAllOf
            //instance = new CallFunctionAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallFunctionAllOf
        /// </summary>
        [Test]
        public void CallFunctionAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CallFunctionAllOf
            //Assert.IsInstanceOf(typeof(CallFunctionAllOf), instance);
        }


        /// <summary>
        /// Test the property 'PackageAddress'
        /// </summary>
        [Test]
        public void PackageAddressTest()
        {
            // TODO unit test for the property 'PackageAddress'
        }
        /// <summary>
        /// Test the property 'BlueprintName'
        /// </summary>
        [Test]
        public void BlueprintNameTest()
        {
            // TODO unit test for the property 'BlueprintName'
        }
        /// <summary>
        /// Test the property 'FunctionName'
        /// </summary>
        [Test]
        public void FunctionNameTest()
        {
            // TODO unit test for the property 'FunctionName'
        }
        /// <summary>
        /// Test the property 'Arguments'
        /// </summary>
        [Test]
        public void ArgumentsTest()
        {
            // TODO unit test for the property 'Arguments'
        }

    }

}
