/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CallMethodWithAllResources
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CallMethodWithAllResourcesTests
    {
        // TODO uncomment below to declare an instance variable for CallMethodWithAllResources
        //private CallMethodWithAllResources instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallMethodWithAllResources
            //instance = new CallMethodWithAllResources();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallMethodWithAllResources
        /// </summary>
        [Test]
        public void CallMethodWithAllResourcesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CallMethodWithAllResources
            //Assert.IsInstanceOf(typeof(CallMethodWithAllResources), instance);
        }


        /// <summary>
        /// Test the property 'ComponentAddress'
        /// </summary>
        [Test]
        public void ComponentAddressTest()
        {
            // TODO unit test for the property 'ComponentAddress'
        }
        /// <summary>
        /// Test the property 'MethodName'
        /// </summary>
        [Test]
        public void MethodNameTest()
        {
            // TODO unit test for the property 'MethodName'
        }

    }

}
