/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DecompileUnknownTransactionIntentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DecompileUnknownTransactionIntentRequestTests
    {
        // TODO uncomment below to declare an instance variable for DecompileUnknownTransactionIntentRequest
        //private DecompileUnknownTransactionIntentRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DecompileUnknownTransactionIntentRequest
            //instance = new DecompileUnknownTransactionIntentRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DecompileUnknownTransactionIntentRequest
        /// </summary>
        [Test]
        public void DecompileUnknownTransactionIntentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DecompileUnknownTransactionIntentRequest
            //Assert.IsInstanceOf(typeof(DecompileUnknownTransactionIntentRequest), instance);
        }


        /// <summary>
        /// Test the property 'ManifestInstructionsOutputFormat'
        /// </summary>
        [Test]
        public void ManifestInstructionsOutputFormatTest()
        {
            // TODO unit test for the property 'ManifestInstructionsOutputFormat'
        }
        /// <summary>
        /// Test the property 'CompiledUnknownIntent'
        /// </summary>
        [Test]
        public void CompiledUnknownIntentTest()
        {
            // TODO unit test for the property 'CompiledUnknownIntent'
        }

    }

}
