/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DecodeAddressResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DecodeAddressResponseTests
    {
        // TODO uncomment below to declare an instance variable for DecodeAddressResponse
        //private DecodeAddressResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DecodeAddressResponse
            //instance = new DecodeAddressResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DecodeAddressResponse
        /// </summary>
        [Test]
        public void DecodeAddressResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DecodeAddressResponse
            //Assert.IsInstanceOf(typeof(DecodeAddressResponse), instance);
        }


        /// <summary>
        /// Test the property 'NetworkId'
        /// </summary>
        [Test]
        public void NetworkIdTest()
        {
            // TODO unit test for the property 'NetworkId'
        }
        /// <summary>
        /// Test the property 'EntityType'
        /// </summary>
        [Test]
        public void EntityTypeTest()
        {
            // TODO unit test for the property 'EntityType'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Hrp'
        /// </summary>
        [Test]
        public void HrpTest()
        {
            // TODO unit test for the property 'Hrp'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

    }

}
