/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DecompileTransactionIntentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DecompileTransactionIntentRequestTests
    {
        // TODO uncomment below to declare an instance variable for DecompileTransactionIntentRequest
        //private DecompileTransactionIntentRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DecompileTransactionIntentRequest
            //instance = new DecompileTransactionIntentRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DecompileTransactionIntentRequest
        /// </summary>
        [Test]
        public void DecompileTransactionIntentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DecompileTransactionIntentRequest
            //Assert.IsInstanceOf(typeof(DecompileTransactionIntentRequest), instance);
        }


        /// <summary>
        /// Test the property 'CompiledIntent'
        /// </summary>
        [Test]
        public void CompiledIntentTest()
        {
            // TODO unit test for the property 'CompiledIntent'
        }
        /// <summary>
        /// Test the property 'ManifestInstructionsOutputFormat'
        /// </summary>
        [Test]
        public void ManifestInstructionsOutputFormatTest()
        {
            // TODO unit test for the property 'ManifestInstructionsOutputFormat'
        }

    }

}
