/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing EcdsaSecp256k1SignatureAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EcdsaSecp256k1SignatureAllOfTests
    {
        // TODO uncomment below to declare an instance variable for EcdsaSecp256k1SignatureAllOf
        //private EcdsaSecp256k1SignatureAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcdsaSecp256k1SignatureAllOf
            //instance = new EcdsaSecp256k1SignatureAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcdsaSecp256k1SignatureAllOf
        /// </summary>
        [Test]
        public void EcdsaSecp256k1SignatureAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EcdsaSecp256k1SignatureAllOf
            //Assert.IsInstanceOf(typeof(EcdsaSecp256k1SignatureAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Test]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }

    }

}
