/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InvalidType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvalidTypeTests
    {
        // TODO uncomment below to declare an instance variable for InvalidType
        //private InvalidType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InvalidType
            //instance = new InvalidType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InvalidType
        /// </summary>
        [Test]
        public void InvalidTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InvalidType
            //Assert.IsInstanceOf(typeof(InvalidType), instance);
        }


        /// <summary>
        /// Test the property 'ExpectedType'
        /// </summary>
        [Test]
        public void ExpectedTypeTest()
        {
            // TODO unit test for the property 'ExpectedType'
        }
        /// <summary>
        /// Test the property 'ActualType'
        /// </summary>
        [Test]
        public void ActualTypeTest()
        {
            // TODO unit test for the property 'ActualType'
        }

    }

}
