/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MapAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MapAllOfTests
    {
        // TODO uncomment below to declare an instance variable for MapAllOf
        //private MapAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MapAllOf
            //instance = new MapAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MapAllOf
        /// </summary>
        [Test]
        public void MapAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MapAllOf
            //Assert.IsInstanceOf(typeof(MapAllOf), instance);
        }


        /// <summary>
        /// Test the property 'KeyType'
        /// </summary>
        [Test]
        public void KeyTypeTest()
        {
            // TODO unit test for the property 'KeyType'
        }
        /// <summary>
        /// Test the property 'ValueType'
        /// </summary>
        [Test]
        public void ValueTypeTest()
        {
            // TODO unit test for the property 'ValueType'
        }
        /// <summary>
        /// Test the property 'Elements'
        /// </summary>
        [Test]
        public void ElementsTest()
        {
            // TODO unit test for the property 'Elements'
        }

    }

}
