/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PopFromAuthZoneAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PopFromAuthZoneAllOfTests
    {
        // TODO uncomment below to declare an instance variable for PopFromAuthZoneAllOf
        //private PopFromAuthZoneAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PopFromAuthZoneAllOf
            //instance = new PopFromAuthZoneAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PopFromAuthZoneAllOf
        /// </summary>
        [Test]
        public void PopFromAuthZoneAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PopFromAuthZoneAllOf
            //Assert.IsInstanceOf(typeof(PopFromAuthZoneAllOf), instance);
        }


        /// <summary>
        /// Test the property 'IntoProof'
        /// </summary>
        [Test]
        public void IntoProofTest()
        {
            // TODO unit test for the property 'IntoProof'
        }

    }

}
