/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PublicKey
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicKeyTests
    {
        // TODO uncomment below to declare an instance variable for PublicKey
        //private PublicKey instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PublicKey
            //instance = new PublicKey();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PublicKey
        /// </summary>
        [Test]
        public void PublicKeyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PublicKey
            //Assert.IsInstanceOf(typeof(PublicKey), instance);
        }

        /// <summary>
        /// Test deserialize a EcdsaSecp256k1PublicKey from type PublicKey
        /// </summary>
        [Test]
        public void EcdsaSecp256k1PublicKeyDeserializeFromPublicKeyTest()
        {
            // TODO uncomment below to test deserialize a EcdsaSecp256k1PublicKey from type PublicKey
            //Assert.IsInstanceOf(typeof(PublicKey), JsonConvert.DeserializeObject<PublicKey>(new EcdsaSecp256k1PublicKey().ToJson()));
        }
        /// <summary>
        /// Test deserialize a EddsaEd25519PublicKey from type PublicKey
        /// </summary>
        [Test]
        public void EddsaEd25519PublicKeyDeserializeFromPublicKeyTest()
        {
            // TODO uncomment below to test deserialize a EddsaEd25519PublicKey from type PublicKey
            //Assert.IsInstanceOf(typeof(PublicKey), JsonConvert.DeserializeObject<PublicKey>(new EddsaEd25519PublicKey().ToJson()));
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
