/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SBORDecodeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SBORDecodeRequestTests
    {
        // TODO uncomment below to declare an instance variable for SBORDecodeRequest
        //private SBORDecodeRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SBORDecodeRequest
            //instance = new SBORDecodeRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SBORDecodeRequest
        /// </summary>
        [Test]
        public void SBORDecodeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SBORDecodeRequest
            //Assert.IsInstanceOf(typeof(SBORDecodeRequest), instance);
        }


        /// <summary>
        /// Test the property 'EncodedValue'
        /// </summary>
        [Test]
        public void EncodedValueTest()
        {
            // TODO unit test for the property 'EncodedValue'
        }
        /// <summary>
        /// Test the property 'NetworkId'
        /// </summary>
        [Test]
        public void NetworkIdTest()
        {
            // TODO unit test for the property 'NetworkId'
        }

    }

}
