/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TakeFromWorktopByAmountAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TakeFromWorktopByAmountAllOfTests
    {
        // TODO uncomment below to declare an instance variable for TakeFromWorktopByAmountAllOf
        //private TakeFromWorktopByAmountAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TakeFromWorktopByAmountAllOf
            //instance = new TakeFromWorktopByAmountAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TakeFromWorktopByAmountAllOf
        /// </summary>
        [Test]
        public void TakeFromWorktopByAmountAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TakeFromWorktopByAmountAllOf
            //Assert.IsInstanceOf(typeof(TakeFromWorktopByAmountAllOf), instance);
        }


        /// <summary>
        /// Test the property 'ResourceAddress'
        /// </summary>
        [Test]
        public void ResourceAddressTest()
        {
            // TODO unit test for the property 'ResourceAddress'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'IntoBucket'
        /// </summary>
        [Test]
        public void IntoBucketTest()
        {
            // TODO unit test for the property 'IntoBucket'
        }

    }

}
