/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TakeFromWorktopByIdsAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TakeFromWorktopByIdsAllOfTests
    {
        // TODO uncomment below to declare an instance variable for TakeFromWorktopByIdsAllOf
        //private TakeFromWorktopByIdsAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TakeFromWorktopByIdsAllOf
            //instance = new TakeFromWorktopByIdsAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TakeFromWorktopByIdsAllOf
        /// </summary>
        [Test]
        public void TakeFromWorktopByIdsAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TakeFromWorktopByIdsAllOf
            //Assert.IsInstanceOf(typeof(TakeFromWorktopByIdsAllOf), instance);
        }


        /// <summary>
        /// Test the property 'ResourceAddress'
        /// </summary>
        [Test]
        public void ResourceAddressTest()
        {
            // TODO unit test for the property 'ResourceAddress'
        }
        /// <summary>
        /// Test the property 'Ids'
        /// </summary>
        [Test]
        public void IdsTest()
        {
            // TODO unit test for the property 'Ids'
        }
        /// <summary>
        /// Test the property 'IntoBucket'
        /// </summary>
        [Test]
        public void IntoBucketTest()
        {
            // TODO unit test for the property 'IntoBucket'
        }

    }

}
