/*
 * Transaction Library
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing TransactionHeader
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionHeaderTests
    {
        // TODO uncomment below to declare an instance variable for TransactionHeader
        //private TransactionHeader instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionHeader
            //instance = new TransactionHeader();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionHeader
        /// </summary>
        [Test]
        public void TransactionHeaderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransactionHeader
            //Assert.IsInstanceOf(typeof(TransactionHeader), instance);
        }


        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Test]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'NetworkId'
        /// </summary>
        [Test]
        public void NetworkIdTest()
        {
            // TODO unit test for the property 'NetworkId'
        }
        /// <summary>
        /// Test the property 'StartEpochInclusive'
        /// </summary>
        [Test]
        public void StartEpochInclusiveTest()
        {
            // TODO unit test for the property 'StartEpochInclusive'
        }
        /// <summary>
        /// Test the property 'EndEpochExclusive'
        /// </summary>
        [Test]
        public void EndEpochExclusiveTest()
        {
            // TODO unit test for the property 'EndEpochExclusive'
        }
        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Test]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }
        /// <summary>
        /// Test the property 'NotaryPublicKey'
        /// </summary>
        [Test]
        public void NotaryPublicKeyTest()
        {
            // TODO unit test for the property 'NotaryPublicKey'
        }
        /// <summary>
        /// Test the property 'NotaryAsSignatory'
        /// </summary>
        [Test]
        public void NotaryAsSignatoryTest()
        {
            // TODO unit test for the property 'NotaryAsSignatory'
        }
        /// <summary>
        /// Test the property 'CostUnitLimit'
        /// </summary>
        [Test]
        public void CostUnitLimitTest()
        {
            // TODO unit test for the property 'CostUnitLimit'
        }
        /// <summary>
        /// Test the property 'TipPercentage'
        /// </summary>
        [Test]
        public void TipPercentageTest()
        {
            // TODO unit test for the property 'TipPercentage'
        }

    }

}
