name: PyPi

on:
  pull_request:
  push:
    branches:
      - main
      - push-pypi # NOTE: Used for debugging. It should be removed before the PR is merged.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch secrets
      uses: radixdlt/public-iac-resuable-artifacts/fetch-secrets@main
      with:
        role_name: ${{ secrets.PYPI_SECRET_ROLE_NAME }}
        app_name: 'radix-engine-toolkit'
        step_name: 'pypi-credentials'
        secret_prefix: 'PYPI'
        secret_name: ${{ secrets.PYPI_SECRET_NAME }}
        parse_json: true
    - name: Publish to pypi
      run: |
        echo "The secret should be available on the PYPI_USERNAME and PYPI_PASSWORD env variable"
        # TODO: Use ${{ env.PYPI_USERNAME }} and ${{ env.PYPI_PASSWORD }} to reference the credentials
